"""A session pinned to an instant, and what overrides it.

The classes here register on the shared declarative base, because that is
where a pinned session looks for history classes. Their names carry a prefix
so they cannot collide with a package generated by another test.

The rule under test is one sentence: inside a pinned session every history
table shows only the version valid at that instant. The cases below are the
ways a query can reach a history table, plus the three ways a statement can
say it means something else.
"""

from __future__ import annotations

import datetime as dt
import warnings
from collections.abc import Iterator

import pytest
from sqlalchemy import (
    ForeignKey,
    create_engine,
    delete,
    insert,
    select,
    text,
    update,
)
from sqlalchemy.orm import (
    Mapped,
    foreign,
    joinedload,
    mapped_column,
    relationship,
    selectinload,
)

from stele.runtime import (
    Base,
    Binding,
    HistoryMixin,
    PinnedSessionError,
    SCD2Config,
)

D = dt.datetime

# Instants either side of the renames below.
EARLY = D(2025, 3, 1)
LATE = D(2026, 6, 1)


class AsOfBranch(Base):
    """A parent that does not version at all."""

    __tablename__ = "asof_branch"

    BranchId: Mapped[int] = mapped_column(primary_key=True)
    BranchName: Mapped[str]


class AsOfAccount(Base):
    __tablename__ = "asof_account"

    AccountId: Mapped[int] = mapped_column(primary_key=True)
    AccountName: Mapped[str]


class AsOfAccountHistory(Base, HistoryMixin):
    __tablename__ = "asof_account_history"

    AccountId: Mapped[int] = mapped_column(primary_key=True)
    StartDate: Mapped[dt.datetime] = mapped_column(primary_key=True)
    EndDate: Mapped[dt.datetime | None]
    AccountName: Mapped[str]
    ParentAccountId: Mapped[int | None]

    parent: Mapped[AsOfAccountHistory | None] = relationship(
        "AsOfAccountHistory",
        primaryjoin=lambda: (
            AsOfAccountHistory.ParentAccountId
            == foreign(AsOfAccountHistory.AccountId)
        ),
        uselist=False,
        viewonly=True,
    )

    __history_of__ = AsOfAccount
    __scd2__ = SCD2Config(
        start_attr="StartDate",
        end_attr="EndDate",
        business_key=("AccountId",),
    )


class AsOfLedger(Base):
    __tablename__ = "asof_ledger"

    LedgerId: Mapped[int] = mapped_column(primary_key=True)
    AccountId: Mapped[int]

    history: Mapped[list[AsOfLedgerHistory]] = relationship(
        "AsOfLedgerHistory",
        primaryjoin=lambda: (
            AsOfLedger.LedgerId == foreign(AsOfLedgerHistory.LedgerId)
        ),
        order_by="AsOfLedgerHistory.StartDate",
        viewonly=True,
    )


class AsOfLedgerHistory(Base, HistoryMixin):
    __tablename__ = "asof_ledger_history"

    LedgerId: Mapped[int] = mapped_column(primary_key=True)
    StartDate: Mapped[dt.datetime] = mapped_column(primary_key=True)
    EndDate: Mapped[dt.datetime | None]
    AccountId: Mapped[int]
    BranchId: Mapped[int] = mapped_column(ForeignKey("asof_branch.BranchId"))

    account: Mapped[AsOfAccountHistory | None] = relationship(
        "AsOfAccountHistory",
        primaryjoin=lambda: (
            AsOfLedgerHistory.AccountId
            == foreign(AsOfAccountHistory.AccountId)
        ),
        uselist=False,
        viewonly=True,
    )
    branch: Mapped[AsOfBranch | None] = relationship(
        "AsOfBranch", viewonly=True
    )

    __history_of__ = AsOfLedger
    __scd2__ = SCD2Config(
        start_attr="StartDate",
        end_attr="EndDate",
        business_key=("LedgerId",),
    )


@pytest.fixture
def binding() -> Iterator[Binding]:
    engine = create_engine("sqlite://")
    Base.metadata.create_all(
        engine,
        tables=[
            Base.metadata.tables[name]
            for name in (
                "asof_branch",
                "asof_account",
                "asof_account_history",
                "asof_ledger",
                "asof_ledger_history",
            )
        ],
    )
    b = Binding(engine=engine)
    with b.session() as s:
        s.add_all(
            [
                AsOfBranch(BranchId=5, BranchName="Main"),
                AsOfAccount(AccountId=1, AccountName="Globex Intl"),
                # renamed in September 2025
                AsOfAccountHistory(
                    AccountId=1,
                    AccountName="Globex",
                    ParentAccountId=None,
                    StartDate=D(2024, 1, 1),
                    EndDate=D(2025, 9, 1),
                ),
                AsOfAccountHistory(
                    AccountId=1,
                    AccountName="Globex Intl",
                    ParentAccountId=None,
                    StartDate=D(2025, 9, 1),
                    EndDate=None,
                ),
                AsOfAccountHistory(
                    AccountId=2,
                    AccountName="Subsidiary",
                    ParentAccountId=1,
                    StartDate=D(2024, 1, 1),
                    EndDate=None,
                ),
                AsOfLedger(LedgerId=42, AccountId=1),
                AsOfLedgerHistory(
                    LedgerId=42,
                    AccountId=1,
                    BranchId=5,
                    StartDate=D(2025, 1, 1),
                    EndDate=D(2026, 2, 1),
                ),
                AsOfLedgerHistory(
                    LedgerId=42,
                    AccountId=1,
                    BranchId=5,
                    StartDate=D(2026, 2, 1),
                    EndDate=None,
                ),
            ]
        )
    yield b
    engine.dispose()


def names(rows: object) -> list[str]:
    return [r.AccountName for r in rows]  # type: ignore[attr-defined]


def parent_name(row: AsOfLedgerHistory) -> str:
    """The traversal a pinned session makes single-valued."""
    assert row.account is not None
    return row.account.AccountName


def self_parent(row: AsOfAccountHistory) -> str:
    assert row.parent is not None
    return row.parent.AccountName


# --- the rule --------------------------------------------------------------


def test_a_pinned_select_shows_one_version(binding: Binding) -> None:
    with binding.as_of(EARLY) as s:
        rows = s.scalars(select(AsOfLedgerHistory)).all()
    assert [r.StartDate for r in rows] == [D(2025, 1, 1)]


@pytest.mark.parametrize(
    "strategy",
    [
        None,
        selectinload(AsOfLedgerHistory.account),
        joinedload(AsOfLedgerHistory.account),
    ],
    ids=["lazy", "selectinload", "joinedload"],
)
def test_every_load_strategy_is_narrowed(
    binding: Binding, strategy: object
) -> None:
    stmt = select(AsOfLedgerHistory)
    if strategy is not None:
        stmt = stmt.options(strategy)  # type: ignore[arg-type]
    with binding.as_of(EARLY) as s:
        got = [parent_name(r) for r in s.scalars(stmt).unique()]
    assert got == ["Globex"]

    with binding.as_of(LATE) as s:
        got = [parent_name(r) for r in s.scalars(stmt).unique()]
    assert got == ["Globex Intl"]


def test_a_join_written_by_hand_is_narrowed(binding: Binding) -> None:
    stmt = select(AsOfLedgerHistory, AsOfAccountHistory).join(
        AsOfAccountHistory,
        AsOfAccountHistory.AccountId == AsOfLedgerHistory.AccountId,
    )
    with binding.session() as s:
        assert len(s.execute(stmt).all()) == 4
    with binding.as_of(EARLY) as s:
        assert [a.AccountName for _, a in s.execute(stmt)] == ["Globex"]


def test_a_self_reference_resolves_at_the_same_instant(
    binding: Binding,
) -> None:
    stmt = select(AsOfAccountHistory).where(
        AsOfAccountHistory.ParentAccountId.is_not(None)
    )
    with binding.as_of(EARLY) as s:
        assert self_parent(s.scalars(stmt).one()) == "Globex"
    with binding.as_of(LATE) as s:
        assert self_parent(s.scalars(stmt).one()) == "Globex Intl"


def test_a_parent_without_history_is_reached_unchanged(
    binding: Binding,
) -> None:
    with binding.as_of(EARLY) as s:
        row = s.scalars(select(AsOfLedgerHistory)).one()
        assert row.branch is not None
        assert row.branch.BranchName == "Main"


# --- saying you mean something else ----------------------------------------


def test_one_entity_can_be_pinned_elsewhere(binding: Binding) -> None:
    with binding.as_of(EARLY, {AsOfAccountHistory: LATE}) as s:
        row = s.scalars(select(AsOfLedgerHistory)).one()
        assert row.StartDate == D(2025, 1, 1)
        assert parent_name(row) == "Globex Intl"


def test_one_entity_can_be_left_unfiltered(binding: Binding) -> None:
    with binding.as_of(EARLY, {AsOfAccountHistory: None}) as s:
        rows = s.scalars(select(AsOfAccountHistory)).all()
    assert sorted(names(rows)) == ["Globex", "Globex Intl", "Subsidiary"]


def test_versions_of_returns_every_version_inside_a_pin(
    binding: Binding,
) -> None:
    with binding.as_of(EARLY) as s:
        assert len(s.scalars(AsOfLedgerHistory.versions_of((42,))).all()) == 2
        assert len(s.scalars(AsOfLedgerHistory.timeline((42,))).all()) == 2
        # and the session is still pinned
        assert len(s.scalars(select(AsOfLedgerHistory)).all()) == 1


def test_as_of_overrides_the_session_rather_than_narrowing_it(
    binding: Binding,
) -> None:
    with binding.as_of(EARLY) as s:
        rows = s.scalars(AsOfAccountHistory.as_of(LATE)).all()
    assert sorted(names(rows)) == ["Globex Intl", "Subsidiary"]


def test_changes_between_keeps_its_own_window(binding: Binding) -> None:
    with binding.as_of(EARLY) as s:
        rows = s.scalars(
            AsOfAccountHistory.changes_between(D(2025, 1, 1), D(2026, 1, 1))
        ).all()
    assert names(rows) == ["Globex Intl"]


# --- what a pinned session refuses -----------------------------------------


def test_current_refuses_inside_a_pinned_session(binding: Binding) -> None:
    with (
        binding.as_of(EARLY) as s,
        pytest.raises(PinnedSessionError) as caught,
    ):
        s.scalars(AsOfAccountHistory.current()).all()
    message = str(caught.value)
    assert "current()" in message
    assert "unpinned session" in message


def test_current_still_works_unpinned(binding: Binding) -> None:
    with binding.session() as s:
        assert names(s.scalars(AsOfAccountHistory.current())) == [
            "Globex Intl",
            "Subsidiary",
        ]


@pytest.mark.parametrize(
    "build",
    [
        lambda: update(AsOfAccountHistory).values(AccountName="Renamed"),
        lambda: delete(AsOfAccountHistory),
        lambda: insert(AsOfAccountHistory).values(
            AccountId=3,
            AccountName="Added",
            ParentAccountId=None,
            StartDate=D(2024, 1, 1),
            EndDate=None,
        ),
    ],
    ids=["update", "delete", "insert"],
)
def test_a_write_refuses_inside_a_pinned_session(
    binding: Binding, build: object
) -> None:
    with (
        binding.as_of(EARLY) as s,
        pytest.raises(PinnedSessionError) as caught,
    ):
        s.execute(build())  # type: ignore[operator]
    assert "selects only" in str(caught.value)

    with binding.session() as s:
        assert sorted(names(s.scalars(select(AsOfAccountHistory)))) == [
            "Globex",
            "Globex Intl",
            "Subsidiary",
        ]


@pytest.mark.parametrize(
    "sql",
    [
        "select count(*) from asof_account_history",
        "update asof_account_history set AccountName = 'Renamed'",
    ],
    ids=["read", "write"],
)
def test_textual_sql_refuses_inside_a_pinned_session(
    binding: Binding, sql: str
) -> None:
    """The pin cannot be applied to a statement it cannot read."""
    with (
        binding.as_of(EARLY) as s,
        pytest.raises(PinnedSessionError) as caught,
    ):
        s.execute(text(sql))
    assert "selects only" in str(caught.value)


def test_a_write_outside_a_pinned_session_still_works(
    binding: Binding,
) -> None:
    with binding.session() as s:
        s.execute(
            update(AsOfAccountHistory)
            .where(AsOfAccountHistory.AccountId == 2)
            .values(AccountName="Renamed")
        )
    with binding.session() as s:
        assert "Renamed" in names(s.scalars(select(AsOfAccountHistory)))


def test_a_flush_of_a_dirty_object_is_not_intercepted(
    binding: Binding,
) -> None:
    """The boundary: the pin sees statements, not the unit of work.

    Nothing flushes on its own, because a pinned session has autoflush off
    and does not commit on exit. An explicit flush or commit writes.
    """
    stmt = select(AsOfAccountHistory).where(AsOfAccountHistory.AccountId == 1)
    with binding.as_of(EARLY) as s:
        row = s.scalars(stmt).one()
        row.AccountName = "Edited"
        s.commit()

    with binding.session() as s:
        assert "Edited" in names(s.scalars(select(AsOfAccountHistory)))


# --- the default instant ---------------------------------------------------


def test_no_argument_means_now(binding: Binding) -> None:
    with binding.as_of() as s:
        rows = s.scalars(select(AsOfAccountHistory)).all()
    assert sorted(names(rows)) == ["Globex Intl", "Subsidiary"]


# --- limits worth pinning down ---------------------------------------------


def test_a_pin_reaches_history_tables_only(binding: Binding) -> None:
    """A current table has no interval, so a pinned session cannot move it."""
    with binding.as_of(EARLY) as s:
        assert (
            s.scalars(select(AsOfAccount)).one().AccountName == "Globex Intl"
        )


def test_an_unpinned_traversal_warns_where_the_data_allows(
    binding: Binding,
) -> None:
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        with binding.session() as s:
            row = s.scalars(
                select(AsOfLedgerHistory).order_by(AsOfLedgerHistory.StartDate)
            ).first()
            assert row is not None
            assert row.account is not None
    assert any("uselist=False" in str(w.message) for w in caught)
